name = "PentagramMap"
uuid = "c27d6304-b610-49b7-9262-97ea78461b5d"
authors = ["Oliver Daisey <oliverjdaisey@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
