name = "PentagramMap"
uuid = "c27d6304-b610-49b7-9262-97ea78461b5d"
authors = ["Oliver Daisey <oliverjdaisey@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
LinearAlgebra = "1.11.0"
Plots = "1.40.20"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
